const COLOR_PALETTE = {
  HIGHLIGHT_LIGHTEST: "#dff9fb",
  HIGHLIGHT_LIGHT: "#c7ecee",
  HIGHLIGHT_MEDIUM: "#7ed6df",
  HIGHLIGHT_DARK: "#22a6b3",

  GARY_LIGHT: "#95afc0",
  GRAY_MEDIUM: "#535c68",
  GRAY_DARK: "#333",
};

export default COLOR_PALETTE;
